### ISSUE TITLE
how can i enable new module by default 

### ISSUE THREAD

**Issue by esameisa** [dcblogdev/laravel-module-generator#4]
When i create new module
`php artisan module:build`
it must run after that `php artisan module:enable ModuleName` ?

**Comment by esameisa** [comment]
@dcblogdev
please help ..

**Comment by dcblogdev** [comment]
Do you meant to enable the module? Are you wanting generated modules to be enabled by default?

**Comment by esameisa** [comment]
yes, exactly @dcblogdev

**Comment by dcblogdev** [comment]
that's actually outside the scope of this package, you would do that in Laravel Modules package, but I'm sure they are enabled by default
