### ISSUE TITLE
Doesn't Generate files on fresh install

### ISSUE THREAD

**Issue by malsgit** [dcblogdev/laravel-module-generator#5]
Hi DC,
Laravel = 9.48
PHP = 8.19
OS = iMac 
localhost env = Laravel Valet

I've installed the package on a fresh install of Laravel 9.48 running the following in terminal
`laravel new modules --jet --teams` 
option (0) = Livewire
`composer require nwidart/laravel-modules`
`php artisan vendor:publish --provider="Nwidart\Modules\LaravelModulesServiceProvider"`

```
{
  "autoload": {
    "psr-4": {
      "App\\": "app/", 
      "Modules\\": "Modules/" **/* Added this line */**
    }
  }
}
```

`composer dump-autoload`
Tested to make sure I could create a module
`php artisan module:make Test`
Generated the files :-)
Proceeded to install this package......
`composer require dcblogdev/laravel-module-generator`
`php artisan vendor:publish --provider="Dcblogdev\ModuleGenerator\ModuleGeneratorServiceProvider"`
creates **config/module-generator.php** NOT **config/generator.php** 

in terminal ran:
`php artisan module:build`
 
```
 Please enter name: 
> Contacts
Starter Contacts module generated successfully.
```
**Nothing happends?**

Even after adding following to .env file
`GENERATOR_PATH=Modules`

Any help appreciated, as I would like to see if it will speed up my development?

Cheers

Mal

**Comment by dcblogdev** [comment]
thanks, @MalBlack for such a detailed explanation, I've followed your steps exactly. I have the same result. 

I'm looking into the cause.

**Comment by dcblogdev** [comment]
okay found the issue its because the name of your project is called `Modules` if you name your project something else it then works.
