### ISSUE TITLE
new table is not plural

### ISSUE THREAD

**Issue by rabol** [dcblogdev/laravel-module-generator#6]
Issuing the command:

```
php artisan module:build  
```

and then enter Demo will create a new module, however you will get an error when accessing /demo

```
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'moduletest.demos' doesn't exist
```

due to the fact that the table name is 'demo' and not 'demos' as Laravel expect.

sure this in the model:
```
protected $table = 'demo';
 ```

will solve it

**Comment by dcblogdev** [comment]
Yes its with the module called Demo, will look at update the generator, maybe as simple as adding a placeholder that converts using `Str::plural` something like `{module_plural}`

I'll do some testing.

**Comment by dcblogdev** [comment]
good news, I've solved this now in your migration file you can use {module_plural} which will get replaced with the plural version of the module name.
